# Generated by Django 4.2.3 on 2023-08-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottoGames', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneOutOfTwenty',
        ),
    ]
