# Generated by Django 4.2.3 on 2023-08-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_profile_account_balance'),
        ('lottoGames', '0006_delete_oneoutoftwenty'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOutOfTwenty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.PositiveBigIntegerField(default=0)),
                ('gameDate', models.DateTimeField(auto_now_add=True)),
                ('luckyNumber', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
