# Generated by Django 4.2.3 on 2023-08-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pictures',
        ),
    ]
