# Generated by Django 4.2.3 on 2023-08-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pictures',
            field=models.ImageField(default='profilePics/blankUser.png', upload_to='profilePics'),
        ),
    ]
