# Generated by Django 4.2.3 on 2023-08-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
